# Generated by Django 5.0.6 on 2024-06-25 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterModelOptions(
            name='scrapingresult',
            options={'verbose_name': 'Resultado de Scraping', 'verbose_name_plural': 'Resultados de Scraping'},
        ),
        migrations.AlterModelOptions(
            name='scrapingrule',
            options={'verbose_name': 'Regra de Scraping', 'verbose_name_plural': 'Regras de Scraping'},
        ),
        migrations.AlterModelOptions(
            name='url',
            options={'verbose_name': 'URL', 'verbose_name_plural': 'URLs'},
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome do Projeto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Diária'), ('weekly', 'Semanalmente'), ('monthly', 'Mensalmente')], max_length=20, verbose_name='Frequência'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='next_run',
            field=models.DateTimeField(verbose_name='Próxima Execução'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Projeto'),
        ),
        migrations.AlterField(
            model_name='scrapingresult',
            name='data',
            field=models.JSONField(verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='scrapingresult',
            name='scraped_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='scrapingresult',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.url', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='scrapingrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='scrapingrule',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Projeto'),
        ),
        migrations.AlterField(
            model_name='scrapingrule',
            name='selector',
            field=models.TextField(verbose_name='Seletor'),
        ),
        migrations.AlterField(
            model_name='scrapingrule',
            name='type',
            field=models.CharField(choices=[('CSS', 'CSS'), ('XPath', 'XPath')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='url',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Projeto'),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.TextField(verbose_name='URL'),
        ),
    ]
