# Generated by Django 5.0.6 on 2024-07-31 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_ai_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='new_selector',
            field=models.TextField(blank=True, null=True, verbose_name='Novo Seletor'),
        ),
        migrations.AddField(
            model_name='url',
            name='new_type',
            field=models.CharField(blank=True, choices=[('CSS', 'CSS'), ('XPath', 'XPath')], max_length=20, null=True, verbose_name='Novo Tipo'),
        ),
        migrations.CreateModel(
            name='URLScrapingRuleTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='URL')),
                ('status', models.CharField(choices=[('valid', 'Válida'), ('invalid', 'Inválida')], max_length=20)),
                ('selector', models.TextField(verbose_name='Seletor')),
                ('type', models.CharField(choices=[('CSS', 'CSS'), ('XPath', 'XPath')], max_length=20, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Projeto')),
            ],
        ),
    ]
