# Generated by Django 5.0.6 on 2024-07-31 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_url_new_selector_url_new_type_urlscrapingruletemp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URLScrapingRuleTemp',
            new_name='URLScrapingRule',
        ),
        migrations.AlterModelOptions(
            name='urlscrapingrule',
            options={'verbose_name': 'Regra de Scraping de URL', 'verbose_name_plural': 'Regras de Scraping de URL'},
        ),
        migrations.RemoveField(
            model_name='scrapingresult',
            name='url',
        ),
        migrations.RemoveField(
            model_name='url',
            name='new_selector',
        ),
        migrations.RemoveField(
            model_name='url',
            name='new_type',
        ),
        migrations.AddField(
            model_name='scrapingresult',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Projeto'),
            preserve_default=False,
        ),
    ]
