# Generated by Django 5.0.6 on 2024-07-31 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_urlscrapingruletemp_urlscrapingrule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingresult',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Projeto'),
        ),
    ]
