# Generated by Django 5.0.6 on 2024-07-31 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_scrapingresult_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='project',
        ),
        migrations.AlterField(
            model_name='scrapingresult',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Projeto'),
        ),
        migrations.DeleteModel(
            name='ScrapingRule',
        ),
        migrations.DeleteModel(
            name='URL',
        ),
    ]
