# Generated by Django 5.0.6 on 2024-06-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_projects', models.IntegerField()),
                ('max_urls', models.IntegerField()),
                ('max_scraping_frequency', models.CharField(choices=[('daily', 'Diária'), ('weekly', 'Semanalmente'), ('monthly', 'Mensalmente')], max_length=20)),
            ],
        ),
    ]
