# Generated by Django 5.0.6 on 2024-06-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'Plano', 'verbose_name_plural': 'Planos'},
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_projects',
            field=models.IntegerField(verbose_name='Máximo de Projetos'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_scraping_frequency',
            field=models.CharField(choices=[('daily', 'Diária'), ('weekly', 'Semanalmente'), ('monthly', 'Mensalmente')], max_length=20, verbose_name='Frequência Máxima de Scraping'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_urls',
            field=models.IntegerField(verbose_name='Máximo de Urls'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Plano'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
    ]
